.github/main.workflow, entrypoint.js, utils.js
This reduces maintenance burden on this repo by adding a function to dynamically fetch supported release lines for the weekly cron job, so that we don't have to manually update this when new lines are cut.
cc @electron/wg-releases
=> feat: dynamically fetch supported release branches

entrypoint.js, server.js
Fix the @ name used to get the Releases WG's attention.
=> fix: use '@releases-wg' for workgroup mentions

entrypoint.js, server.js, utils.js
The message text for crontab + user-initiated audits was very similar so this PR extracts it into a common reusable function.
=> chore: extract-method to remove duplicate message code

README.md, server.js
Allow for users to manually query for the status of all currently supported release branches instead of needing to query branch-by-branch.
cc @ckerr @MarshallOfSound
=> feat: manual status query for all supported branches

server.js, utils/commits-helpers.js, utils/helpers.js, utils/unmerged-commits.js, utils/unreleased-commits.js
This allows for users to query for the number of unmerged pull requests targeting a specified release branch, so that we can properly assess that we've merged all outstanding backports before we begin a release.
cc @ckerr @MarshallOfSound
=> feat: allow users to query for unmerged prs

README.md, server.js, utils/needs-manual-prs.js, utils/unmerged-prs.js
Closes https://github.com/electron/unreleased/issues/12.
This PR will allow members of the ElectronHQ slack workspace to run:
```sh
/check-needs-manual 5-0-x
```
to check for pull requests which have been merged to master and labeled 
with `target/BRANCH_NAME` that trop failed for and which still need manual backports.
cc @jkleinsc @ckerr
=> feat: enable audit of needs-manual PRs

server.js, utils/needs-manual-prs.js, utils/unmerged-prs.js, utils/unreleased-commits.js
This PR refactors the way that messages are put together to reduce redundancies for the new `/audit-pre-release`.
=> refactor: message building for cleaner output

README.md, constants.js, server.js, utils/commits-helpers.js, utils/helpers.js
Remove Electron-specific hardcoded constants to allow for use in other repositories.
cc @MarshallOfSound
=> chore: make electron-specific constants agnostic

server.js, utils/issue-search.js, utils/needs-manual-prs.js
(includes #21 because I can't work out how to submit a stacked PR without
having access to the repo)
This adds the plumbing for a new /review-queue slash-command endpoint. The
expected usage is e.g. `/review-queue api-review`. That command will search
the configured repo for open prs with the label `api-review/requested 🗳` and
post them to channel.
=> feat: add /review-queue for searching for {label}/requested PRs

package-lock.json, package.json, server.js, utils/helpers.js, utils/unreleased-commits.js
Makes the verify-semver command run faster by doing the expensive "API request for every commit" step in a concurrent queue instead of sequentially.
=> perf: make the semver check go faster by checking commits in a concurrent queue

entrypoint.js
This fixes a minor bug found by [LGTM](https://lgtm.com/projects/g/electron/unreleased/?mode=list).
```js
let text;
text += 'foo'
```
results in `undefinedfoo`, but what we really wanted was `foo`
=> fix: instead of appending to undef var, init it

utils/helpers.js
This PR adds more verbose logging for a possible rate-limit error
=> chore: add error handling for supported branches

utils/helpers.js, utils/test-gh-apis.js, utils/unreleased-commits.js
#56 did not use await on octokit pagination calls but it should, so this PR fixes that.
=> chore: fixup octokit pagination to await

utils/helpers.js
Fixes an issue where `isDraft` would always be `undefined`.
This was missed in tests because https://github.com/electron/unreleased/blob/cb036df11a4abdee6493acddb4bbcc712862d3f3/utils/test-gh-apis.js#L36 tests for truthiness, and `undefined` coerced to false, which coincidentally was correct for the test case.
=> fix: draft is a property on data

package-lock.json, package.json, server.js, test/gh-api-calls.js, utils/unreleased-commits.js
Fix heroku timeout errors when fetching tags by switching from REST to GraphQL to save ~15 seconds per call.
=> refactor: use graphql to fetch tags

README.md, constants.js
When we moved our release cadence from 12 weeks to 8 weeks, [we temporarily extended our supported versions from the last three versions to the last four versions](https://www.electronjs.org/blog/8-week-cadence#2021-plan-for-releases). That extension ends next week -  beginning next week, our supported versions will Electron 17, 18 & 19.
This PR bumps the number of supported versions from 5 back to 4.
_NOTE: Please do not merge until after the last 15-x-y and 16-x-y releases have been cut on Tuesday, May 24th_
=> chore: decrease number of supported versions

.github/workflows/test.yml
Fixes failure as seen here: https://github.com/electron/unreleased/actions/runs/3618442124/jobs/6501081452
I've already added `UNRELEASED_GITHUB_APP_CREDS` to repo secrets.
=> spec: fix failing GH API specs

.github/workflows/lint.yml, .github/workflows/test.yml
Support for just `version` was dropped a couple years ago, so the current key has no effect, [see warnings on workflow runs](https://github.com/electron/unreleased/actions/runs/4057415913).
=> build: use node-version with actions/setup-node

test/gh-api-calls.js
Looks like this test wasn't using a `branch` for `getSemverForCommitRange` meaning it would fetch all closed PRs on the repo, which is why it was so slow.
=> test: don't fetch all closed PRs

.github/workflows/lint.yml, .github/workflows/needs-manual-audit.yml, .github/workflows/test.yml, .github/workflows/unreleased-audit.yml
* Pins SHAs for actions
* Restricts permissions for lint and test
* Drops `GITHUB_TOKEN` after its usage was removed in 82c72509cbe7de8be3fb4c400be41d3b1b7d49ca
=> build: update GitHub actions workflows

utils/helpers.js
Supplemental PR to https://github.com/electron/sudowoodo/pull/241
This PR extends the number of support releases to continue to support Electron 22.
Previously, we've just extended the number of support versions from 3 to 4 (which would also work in this case). However, this will need to be modified after the release of Electron 26 - at that time, the supported versions will be [27-alpha/beta, 26, 25, 24, 22], with 23 missing.
=> build: extend release versions for E22

package-lock.json, package.json
Refs https://github.com/electron/electron/pull/38435.
Just being proactive here and bumping the major versions on these packages so we can pick up the latest `@octokit/request`. I don't think it's at risk of hitting the bug which hit `e/e`, since this repo only makes read usage of `octokit`, but might as well pick it up.
=> build: upgrade octokit dependencies

utils/helpers.js
This PR removes extended support for Electron 22.
Reverts commit 38622d68364445f0665e633824e1447cb5f27f90.
=> build: revert extended release versions for E22

.github/workflows/lint.yml, .github/workflows/needs-manual-audit.yml, .github/workflows/test.yml, .github/workflows/unreleased-audit.yml
Bumps versions to get things off EOL Node.js versions and preempts deprecation warnings.
=> ci: update workflows

server.js, utils/helpers.js
Protect against timing attacks.
=> refactor: use crypto.timingSafeEqual to check auth header

action-audit.js, constants.js
During an unreleased commits audit, if unreleased commits have been pending for more than `N` days (currently set to 8, happy to tweak) add a warning to the message.
=> feat: warn if branch has had unreleased commits for N days

action-audit.js
This wasn't handling the possibility of their being no unreleased commits (and hence no earliest commit), so wrap it in a conditional now.
=> fix: handle edge case of no unreleased commits

app.json
We don't use Papertrail anymore, since everything goes into Datadog.
=> chore: remove papertrail addon from app.json

.eslintrc.json, package-lock.json, package.json, server.js, test/gh-api-calls.js, test/needs-manual.spec.js, test/unmerged.spec.js, test/unreleased-commits.spec.js, utils/helpers.js
Drops several packages in favor of using builtins in modern Node.js, most notably `node:test`.
Will follow this up with a PR to update the remaining dependencies, I just didn't want to blow this one out with any formatting changes that may occur as a result. I had to update `eslint` in this PR so it understood builtin `fetch`.
=> refactor: modernize codebase and drop dependencies

constants.js, utils/unreleased-commits.js
We no longer do bump commits on `e/e` (last one was Oct 2022) so we don't need this since it only reviews commits on supported branches.
=> chore: remove BUMP_COMMIT_PATTERN

constants.js, test/unreleased-commits.spec.js, utils/unreleased-commits.js
Reduces the noise in the unreleased commits audit by excluding commit prefixes (`build:`, `ci:`, and `test:`).
=> chore: exclude some commit prefixes from unreleased audit

.github/workflows/needs-manual-audit.yml
It's not very useful running on Wednesday since that's when we have automated releases set up.
=> chore: run manual backport audit on Mondays
