electron/unreleased

- utils.js
When fetching unreleased commits, it should not stop simply when a tag is present: it should stop when both a tag is present AND that tag is associated with a _published_ release and not one in draft status.
cc @alexeykuzmin
> fix: unreleased should take draft status into acct

- server.js
Bail early if the requested branch is not a valid release branch.
cc @MarshallOfSound @ckerr
> fix: bail early for invalid branches

- README.md
Improve documentation for new functionality added in https://github.com/electron/unreleased/pull/9.
cc @electron/wg-releases
> docs: add documentation for new unmerged command

- utils/commits-helpers.js
- utils/unreleased-commits.js
Follow-up for review comments on https://github.com/electron/unreleased/pull/9.
cc @ckerr
> refactor: clean up commit helpers

- .prettierrc.json
- constants.js
- entrypoint.js
- package-lock.json
- package.json
- server.js
- utils/commits-helpers.js
- utils/helpers.js
- utils/needs-manual-prs.js
- utils/unmerged-prs.js
- utils/unreleased-commits.js
What it says on the tin.
cc @MarshallOfSound
> chore: make it prettier

- .github/workflows/lint.yml
What it says on the tin.
cc @MarshallOfSound @ckerr
> chore: add linting

- utils/api-helpers.js
- utils/commits-helpers.js
- utils/unmerged-prs.js
- utils/unreleased-commits.js
Also, update the comment to make it clearer that the helpers work on any paged
response.
> refactor: move api helpers to separate file

- .github/workflows/api-review-audit.yml
- constants.js
- entrypoint.js
- server.js
- utils/review-queue-prs.js
Perform automatic weekly audits of PRs needing API review. Refactor a few things accordingly.
cc @nornagon
> feat: auto-audit API Review PRs

- utils/helpers.js
- utils/unreleased-commits.js
> perf: improve tag lookup perf (cache all the things)

- utils/helpers.js
Account for default branch pagination when fetching supported branches.
> fix: ensure enough branches are fetched

- utils/unreleased-commits.js
We were indexing into the wrong property,
> fix: commit.message -> payload.commit.message

- utils/helpers.js
This PR adds additional error handling for fetching commits
> build: add error handling for commit range

- package-lock.json
- package.json
- utils/helpers.js
Closes #46
This PR was a collaboration during Electron Hack Week and adds Octokit to the REST API calls for GitHub, to prevent us from being rate-limited.
> build: add octokit to GitHub REST API calls

- .husky/pre-commit
- package-lock.json
- package.json
Closes #50.
Added lint-staged and husky to enforce code style on changed files.
cc @codebytere
> chore: add prettier pre-commit hook

- .prettierrc
- .prettierrc.json
Remove prettierrc in favor of prettierrc.json.
cc @codebytere
> chore: remove dup prettierrc

- package-lock.json
- utils/helpers.js
- utils/unreleased-commits.js
Does what it says on the tin. Or maybe it doesn't? It's untested.
> refactor: use octokit when fetching tags

- utils/api-helpers.js
- utils/unmerged-prs.js
A followup to this morning's PR. I don't know if this one will work either but since the first one did, I figured I'm on a roll and should press my luck
> refactor: use octokit when fetching pulls to a branch

- .github/workflows/test.yml
- package-lock.json
- package.json
- server.js
- utils/helpers.js
- utils/test-gh-apis.js
This PR adds a utility to verify that our calls to the Github APS work correctly.
In order to use, you will need to set the UNRELEASED_GITHUB_TOKEN env variable to a Github Personal Access Token
> test: add utility to test GitHub API calls

- server.js
- utils/helpers.js
Fixes timeouts we've been seeing in the Sudowoodo semver verification process.
> fix: prevent timeout properly

- entrypoint.js
- server.js
- test/gh-api-calls.js
- utils/helpers.js
- utils/unreleased-commits.js
> fix: always be a patch release when the last release was prerelease

- constants.js
- package-lock.json
- package.json
- server.js
- utils/helpers.js
- utils/issue-search.js
- utils/octokit.js
- utils/unmerged-prs.js
- utils/unreleased-commits.js
> refactor: migrate to GitHub app for Heroku usage

- .github/workflows/needs-manual-audit.yml
- .github/workflows/unreleased-audit.yml
Same change as in #71, I believe that's why the current scheduled runs are failing.
> build: fix scheduled workflows

- README.md
> docs: add status badges in README

- README.md
- entrypoint.js
Since it's required, document it.
> chore: document UNRELEASED_GITHUB_APP_CREDS

- package.json
> chore: improvements to package.json

- server.js
Adds a GET endpoint for per-branch unreleased commit data.
My intention is to used this to display related information in releases.electronjs.org.
> feat: add unreleased GET endpoint
